version: '3'
services:
  backend:
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/citybikeapp
    build: .
    ports:
      - '5001:5001'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    depends_on:
      - backend
    # disable logs
    command: mongod --quiet --logpath /tmp/mongo.log
